# TEMPLATE

secret_key_base: abcdefghijklmnopqrstuvwxyz

telegram:
  bots:
    # put your Telegram bot API secret and username here
    default:
      username: MyTelegramBot
      token: abcdefghijklmnopqrstuvwxyz

onboarding_token: abcdefghijklmnopqrstuvwxyz
