inherit_from: .rubocop_todo.yml

require: rubocop-rails

Layout/LineLength:
  Max: 130
  Exclude:
    - 'app/components/**/*.rb'
    - 'spec/models/message_spec.rb'
    - 'spec/vcr_setup.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
