version: '3.7'

services:
  app:
    image: tactilenews/hundred-eyes:latest
    environment:
      NODE_ENV: "production"
      RAILS_ENV: "${RAILS_ENV}"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_INBOUND_EMAIL_PASSWORD: "${RAILS_INBOUND_EMAIL_PASSWORD}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      SENDGRID_USERNAME: "${SENDGRID_USERNAME}"
      SENDGRID_PASSWORD: "${SENDGRID_PASSWORD}"
      SENDGRID_DOMAIN: "${SENDGRID_DOMAIN}"
      SENDGRID_FROM: "${SENDGRID_FROM}"
      BASIC_AUTH_LOGIN_USER: "${BASIC_AUTH_LOGIN_USER}"
      BASIC_AUTH_LOGIN_PASSWORD: "${BASIC_AUTH_LOGIN_PASSWORD}"
      HUNDRED_EYES_PROJECT_NAME: "${HUNDRED_EYES_PROJECT_NAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      TELEGRAM_BOT_API_KEY: "${TELEGRAM_BOT_API_KEY}"
      TELEGRAM_BOT_USERNAME: "${TELEGRAM_BOT_USERNAME}"
      ONBOARDING_TOKEN: "${ONBOARDING_TOKEN}"
      APPLICATION_HOSTNAME: "${APPLICATION_HOSTNAME}"
      POSTGRES_DB: app_production
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - ./log:/app/log
      - ./storage:/app/storage

  db:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: app_production
