version: '3.7'

services:
  app:
    environment:
      BINDING: 0.0.0.0
      PORT: 3000
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
    command: bundle exec rails server
    depends_on: [ db ]

  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
