version: '3.7'

x-defaults: &x-defaults
  build:
    context: .
  environment:
    HUNDRED_EYES_PROJECT_NAME: "${HUNDRED_EYES_PROJECT_NAME}"
    RAILS_ENV: "${RAILS_ENV:-development}"
    NODE_ENV: development
    MAILSERVER_HOST: mailserver
    MAILSERVER_PORT: 25
    POSTGRES_HOST: db
    WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    SELENIUM_HOST: selenium
    SELENIUM_PORT: 4444
  stdin_open: true
  tty: true
  volumes:
    - .:/app

services:
  telegram:
    <<: *x-defaults
    command: rake telegram:bot:poller

  app:
    <<: *x-defaults
    depends_on: [ db, mailserver ]
    ports:
      - 3000:3000
      - 3035:3035

  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: [ '5432:5432' ]

  mailserver:
    image: djfarrelly/maildev
    ports: [ '1080:80', '1025:25' ]
  
  selenium-hub:
    image: selenium/hub:3.14.0
    container_name: hub
    ports:
    - 4444:4444
  node-chrome:
    image: selenium/node-chrome-debug:3.14.0
    links:
    - selenium-hub

