---
- name: Create shared volume directories
  file:
    path: /home/ansible/traefik/
    state: directory

- name: Add traefik admin user with htpasswd file
  htpasswd:
    path: /home/ansible/traefik/passwords
    name: "{{ traefik.user }}"
    password: "{{ traefik.password }}"

- name: Copy docker-compose.yml files
  copy:
    src: "{{ item }}"
    dest: /home/ansible/
  with_items:
    - ../docker-compose.yml
    - ../docker-compose.prod.yml
    - ../docker-compose.traefik.yml

- name: Run `docker-compose up`
  environment:
    DOCKER_IMAGE_TAG: "{{ vps.docker_image_tag | default('latest') }}"
    RAILS_ENV: "{{ rails.environment }}"
    HUNDRED_EYES_PROJECT_NAME: "{{ rails.hundred_eyes_project_name }}"
    TELEGRAM_BOT_API_KEY: "{{ rails.telegram_bot.api_key }}"
    TELEGRAM_BOT_USERNAME: "{{ rails.telegram_bot.username }}"
    POSTGRES_HOST: "{{ rails.postgres.host }}"
    POSTGRES_PORT: "{{ rails.postgres.port }}"
    POSTGRES_USER: "{{ rails.postgres.user }}"
    POSTGRES_PASSWORD: "{{ rails.postgres.password }}"
    POSTGRES_DB: "{{ rails.postgres.db }}"
    ACME_EMAIL_ADDRESS: "{{ traefik.acme_email_address }}"
    TRAEFIK_HOSTNAME: "{{ dns.traefik_hostname }}"
    APPLICATION_HOSTNAME: "{{ dns.application_hostname }}"
    POSTMARK_API_TOKEN: "{{ rails.postmark.api_token }}"
    POSTMARK_BROADCASTS_STREAM: "{{ rails.postmark.broadcasts_stream }}"
    POSTMARK_TRANSACTIONAL_STREAM: "{{ rails.postmark.transactional_stream }}"
    EMAIL_FROM_ADDRESS: "{{ rails.email_from_address }}"
    SECRET_KEY_BASE: "{{ rails.secret_key_base }}"
    RAILS_INBOUND_EMAIL_PASSWORD: "{{ rails.inbound_email_password }}"
    BASIC_AUTH_LOGIN_USER: "{{ rails.login.user }}"
    BASIC_AUTH_LOGIN_PASSWORD: "{{ rails.login.password }}"
  community.general.docker_compose:
    project_src: /home/ansible
    build: no
    debug: yes
    pull: yes
    restarted: yes
    files:
      - docker-compose.yml
      - docker-compose.prod.yml
      - docker-compose.traefik.yml

- name: Prune outdated images
  community.general.docker_prune:
    containers: yes
    images: yes

- name: Create and migrate database
  command:
    cmd: docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec app bin/rails db:migrate
    chdir: /home/ansible

- name: Set Telegram webhook
  command:
    cmd: docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec app bin/rails telegram:bot:set_webhook
    chdir: /home/ansible
