- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    password:  "{{ create_password | password_hash('sha512') }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_local_key }}"

- name: Set additional authorized keys
  authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ copy_additional_keys }}"
