development:
  telegram:
    bots:
      default: # only for our build server
        username: MyTelegramBot
        token: TOKEN
test:
  telegram:
    bots:
      default: # only for our build server
        username: MyTelegramBot
        token: TOKEN
