name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RUBYOPT: "-W:no-deprecated"
      RAILS_ENV: staging
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_TARGET: ${{ secrets.DEPLOY_TARGET }}
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start SSH agent and add deploy user's private key
        run: |
          mkdir $HOME/.ssh
          echo ${{ secrets.DEPLOY_USER_PRIVATE_KEY }} | base64 --decode > $HOME/.ssh/deploy_rsa
          chmod 400 $HOME/.ssh/deploy_rsa > /dev/null
          ssh-agent -a $SSH_AUTH_SOCK
          ssh-add $HOME/.ssh/deploy_rsa

      - name: Add deployment target's public key
        run: echo ${{ secrets.DEPLOY_TARGET_PUBLIC_KEY }} | base64 --decode >> $HOME/.ssh/known_hosts

      - name: Install ruby
        uses: actions/setup-ruby@v1
        with: { ruby-version: 2.7.2 }

      - name: Cache Ruby dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install NPM dependencies
        run: yarn install

      - name: Build packs
        run: bin/rails webpacker:compile

      - name: Deploy app using rsync
        run: ./scripts/deploy
